### ISSUE TITLE
希望大佬来一个mac版的

### ISSUE THREAD

**Issue by xiahao90** [BugFor-Pings/Sqlmap_Gui#1]
希望大佬来一个mac版的

**Comment by Tukali** [comment]
+1

**Comment by BugFor-Pings** [comment]
我的建议是：用gpt来写个go或者Java的来调用就行了。这玩意只是复制粘贴的原理而已。如果还是觉得麻烦的话，建议在mac上装一个windows的虚拟机

**Comment by BugFor-Pings** [comment]
python sqlmap.py --gui
